name: 🧪 CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["8.1","8.2", "8.3"]

    name: ⚙️ Running test for PHP ${{ matrix.php }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      # Determine the range of commits to check since last push/pull request
      - name: Determine commit range
        id: commit-range
        run: |
          LAST_COMMIT=$(git rev-parse ${{ github.event.before }} || true)
          if [ -z "$LAST_COMMIT" ]; then
            LAST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_ENV
          echo "CURRENT_COMMIT=${{ github.sha }}" >> $GITHUB_ENV

      # Check commit messages within the determined range
      - name: Check commit messages
        id: commit-check
        run: |
          git log --format='%s' "${LAST_COMMIT}..${CURRENT_COMMIT}" | grep -E '^(feat|fix|docs|style|refactor|test|build|perf|ci|chore|revert|merge|wip): ' || echo "No conventional commits found."

      # Verify commit messages
      - name: Verify commit messages
        run: |
          if [ -z "${{ steps.commit-check.outputs }}"]; then
            echo "Some commit messages do not follow Conventional Commits specification."
            exit 1
          fi

      - name: 🧰 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: 📦 Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: 📥 Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: 🔍 Check php-cs-fixer
        run: composer php-cs-fixer-dry-run

      - name: ✅ Tests
        run: composer test-with-coverage

      - name: 📤 Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.php == '8.2'
