name: 🧪 CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["8.1","8.2", "8.3"]

    name: ⚙️ Running test for PHP ${{ matrix.php }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: Check commit messages
        id: commit-check
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          from-ref: ${{ github.event.before || github.sha }}
          to-ref: ${{ github.sha }}

      - name: Verify commit messages
        run: |
          if [ "${{ steps.commit-check.outputs.isConventional }}" != "true" ]; then
            echo "Some commit messages do not follow Conventional Commits specification."
            exit 1
          fi

      - name: 🧰 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: 📦 Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: 📥 Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: 🔍 Check php-cs-fixer
        run: composer php-cs-fixer-dry-run

      - name: ✅ Tests
        run: composer test-with-coverage

      - name: 📤 Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.php == '8.1'
